name: template-sync-action

on:
  schedule:
  - cron:  "*/3 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: actions-template-sync
        uses: actions/actions-template-sync
        with:
          github_token: ${{ secrets.TEMPLATE_SYNC_SECRET }}
          source_repo_path: trustoverip/mkdocs-material
